// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyA4EOUYHXsXxCPEBIOM8EuYwQP8zAkXZTo',
//     appId: '1:181998623474:web:b9dd880e3fbd3349318e6b',
//     messagingSenderId: '181998623474',
//     projectId: 'fir-9a6a6',
//     authDomain: 'fir-9a6a6.firebaseapp.com',
//     storageBucket: 'fir-9a6a6.appspot.com',
//     measurementId: 'G-D3PJME2MHT',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAm9P4josWFgU2cMz0HzhKafCsXql1IkSc',
//     appId: '1:181998623474:android:8db65b3e732c1880318e6b',
//     messagingSenderId: '181998623474',
//     projectId: 'fir-9a6a6',
//     storageBucket: 'fir-9a6a6.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDJj4FnB7HcdCFJ_1tbQd8owNegv5fb2U8',
//     appId: '1:181998623474:ios:1855f178d160796e318e6b',
//     messagingSenderId: '181998623474',
//     projectId: 'fir-9a6a6',
//     storageBucket: 'fir-9a6a6.appspot.com',
//     iosClientId:
//         '181998623474-rg8rk088vbgk0p2nianp2t5n3fcseq8f.apps.googleusercontent.com',
//     iosBundleId: 'com.example.flutterApplication1',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDJj4FnB7HcdCFJ_1tbQd8owNegv5fb2U8',
//     appId: '1:181998623474:ios:3d9d8b61050c14bd318e6b',
//     messagingSenderId: '181998623474',
//     projectId: 'fir-9a6a6',
//     storageBucket: 'fir-9a6a6.appspot.com',
//     iosClientId:
//         '181998623474-mhjtkifggi9o139hd6q5dh585l8c3lgg.apps.googleusercontent.com',
//     iosBundleId: 'com.example.flutterApplication1.RunnerTests',
//   );
// }
